// <auto-generated />
namespace StudentAttendanceSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Fifoo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fifoo));
        
        string IMigrationMetadata.Id
        {
            get { return "202202230223251_Fifoo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
